application: social-favorites
version: 1
runtime: python
api_version: 1
  
handlers:
- url: /static
  static_dir: static
  secure: always

- url: /favorites/.*
  script: main.py
  login: required
  secure: always

- url: /users/.*
  script: main.py
  login: admin
  secure: always

- url: /api/.*
  script: main.py
  secure: always

builtins:
- datastore_admin: on
- appstats: on
